version: "3"

services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: sh -c "alembic upgrade head && fastapi run --host='0.0.0.0' --port=8000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME_SECONDS: ${JWT_LIFETIME_SECONDS}
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}

  db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata:
