version: "3"

services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "fastapi dev --host='0.0.0.0' --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file:
      - .env

  db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
